### ISSUE TITLE
Change voting cycles

### ISSUE THREAD

**Issue by nibalizer** [nibalizer/Twitch-Picks-CSGO#3]
Right now votes work on a timer - a configurable window before voting is over. 

Change this to have two way communication between csgo-poker and twitch-chat.

Proposed flow:

1) t-c keeps running tallies of votes
2) csgo-poker sees a 'reinitialized'  signalling round end/start of freezetime (buy period)
3) csgo-poker pulls vote data strurcture from t-c
4) csgo-poker hits an endpoint on t-c signaling 'round start'
5) t-c clears old vote and starts new vote whenever /round_start gets a 'PUT' or whatever payload
6) go to step 1

This means voting will always apply to the next round. This is slightly broken because there are things that can cause 'reinitialized' to happen without the round restarting - will need to explore those problems. Possibly fixed by bringing in GSI.

**Comment by nibalizer** [comment]
Working on in https://github.com/nibalizer/Twitch-Picks-CSGO/pull/9

**Comment by stephentoth** [comment]
Why not just use a post request and send a status through /status instead of reinitalize, which can only be used for one function

Also commented on a comment in #9

**Comment by nibalizer** [comment]
I'd say this is complete. @stephentoth if you want to make that improvement go for it!
